version: '3.3'

services:
  app:
    build: 
      context: .
      dockerfile: Dev.Dockerfile
    container_name: app
    networks:
      - piadoca-network
    ports:
      - 8080:8080
    volumes:
      - .:/app
    
networks:
  piadoca-network:
    driver: bridge