version: '3.3'

services:
  app:
    build: 
      context: .
      dockerfile: Dev.Dockerfile
    container_name: app
    networks:
      - piadoca-network
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=piadocas  
      - POSTGRES_PASSWORD=piadocas
      - POSTGRES_DB=piadocas
      - DATABASE_HOST=postgres 
    ports:
      - '5432:5432'
    networks:
      - piadoca-network
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: piadocas@admin.com
      PGADMIN_DEFAULT_PASSWORD: piadocas
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
      - piadoca-network
    restart: unless-stopped  

networks:
  piadoca-network:
    driver: bridge
